#!/usr/bin/env python3
"""Generate MCP Registry ``server.json`` and public tool reference docs.

Module: scripts.gen_mcp_server_json
Depends: argparse, json, jsonschema, sys, tempfile, tomllib, pathlib

Writes repo-root ``server.json`` (D13) and ``docs/mcp-tools.md`` (D18) from the
public ``ToolSpec`` catalog in ``mergecraft.mcp.public``. ``make mcp-server-json``
/ ``mcp-server-json-check`` call this entry point via ``uv run python``.

Exports:
    main — regenerate (default) or ``--check`` committed artifacts.
    build_server_json — construct the registry payload dict.
    render_mcp_tools_md — render the generated tool reference page.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, Any

import jsonschema

from mergecraft.mcp.context import PayloadEvent, RepoIdentity, ResolvedPayload, ToolContext
from mergecraft.mcp.public import PUBLIC_TOOL_NAMES, build_public_tools
from mergecraft.mcp.tool_state import init_tool_state
from mergecraft.modes import compute_modes
from mergecraft.types import XrepoConfig
from mergecraft.utils.github import GitHubClient

if TYPE_CHECKING:
    from mergecraft.mcp.shared import ToolSpec

REPO_ROOT = Path(__file__).resolve().parents[1]
SERVER_JSON_PATH = REPO_ROOT / "server.json"
MCP_TOOLS_MD_PATH = REPO_ROOT / "docs" / "mcp-tools.md"
SCHEMA_PATH = REPO_ROOT / "tests" / "fixtures" / "mcp" / "server.schema.2025-12-11.json"
SCHEMA_URI = "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json"
REGISTRY_NAME = "io.github.alexhawat/mergecraft"
PYPI_IDENTIFIER = "merge-craft"
GENERATED_HEADER = "<!-- Generated by scripts/gen_mcp_server_json.py; do not edit by hand. -->\n"


def pyproject_version() -> str:
    """Return ``project.version`` from ``pyproject.toml``."""
    data = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version.strip():
        msg = "pyproject.toml missing project.version"
        raise ValueError(msg)
    return version


def _minimal_tool_context() -> ToolContext:
    tmpdir = tempfile.mkdtemp(prefix="mergecraft-gen-mcp-")
    state = init_tool_state(owner="local", name="mergecraft", dir=tmpdir)
    return ToolContext(
        agent_id="claude",
        repo=RepoIdentity(owner="local", name="mergecraft"),
        payload=ResolvedPayload(
            event=PayloadEvent(trigger="unknown"),
            shell="disabled",
            push="disabled",
        ),
        github=GitHubClient(token=""),
        github_installation_token="",
        git_token="",
        api_token="",
        modes=compute_modes("claude"),
        tool_state=state,
        mcp_server_url="",
        mcp_auth_token="",
        mcp_orchestrator_auth_token="",
        tmpdir=tmpdir,
        xrepo=XrepoConfig(mode="explicit", read=[], write=[]),
    )


def _public_tool_specs() -> list[ToolSpec]:
    ctx = _minimal_tool_context()
    specs = build_public_tools(ctx)
    names = {spec.name for spec in specs}
    if names != set(PUBLIC_TOOL_NAMES):
        msg = f"public tool names mismatch: {names} != {set(PUBLIC_TOOL_NAMES)}"
        raise RuntimeError(msg)
    return sorted(specs, key=lambda spec: spec.name)


def build_server_json() -> dict[str, Any]:
    """Build the MCP Registry ``server.json`` payload (D13)."""
    version = pyproject_version()
    return {
        "$schema": SCHEMA_URI,
        "name": REGISTRY_NAME,
        "description": ("Public mergeCraft MCP: six review-only tools over completed-review IR."),
        "version": version,
        "packages": [
            {
                "registryType": "pypi",
                "identifier": PYPI_IDENTIFIER,
                "version": version,
                "transport": {
                    "type": "stdio",
                    "args": [
                        "mergecraft",
                        "mcp",
                        "serve",
                        "--role",
                        "public",
                        "--transport",
                        "stdio",
                    ],
                },
            }
        ],
    }


def render_server_json() -> str:
    """Serialize ``server.json`` with a trailing newline."""
    return json.dumps(build_server_json(), indent=2, ensure_ascii=False) + "\n"


def render_mcp_tools_md() -> str:
    """Render ``docs/mcp-tools.md`` from public ``ToolSpec`` schemas (D18)."""
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# Public MCP tools",
        "",
        "Generated from `ToolSpec` definitions in `src/mergecraft/mcp/public.py`.",
        "Install and connect via `docs/mcp.md`.",
        "",
    ]
    for spec in _public_tool_specs():
        lines.extend(
            [
                f"## `{spec.name}`",
                "",
                spec.description,
                "",
                "### Input schema",
                "",
                "```json",
                json.dumps(spec.input_schema, indent=2, ensure_ascii=False),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def validate_server_json(data: dict[str, Any]) -> None:
    """Validate *data* against the vendored offline schema snapshot."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    jsonschema.validate(instance=data, schema=schema)


def _check_or_write(path: Path, expected: str, *, check: bool) -> bool:
    if check:
        if not path.is_file():
            print(f"missing {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            print(f"drift {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    """Regenerate (default) or ``--check`` ``server.json`` and ``docs/mcp-tools.md``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when committed artifacts differ from rendered output.",
    )
    args = parser.parse_args(argv)

    server_text = render_server_json()
    tools_text = render_mcp_tools_md()
    validate_server_json(json.loads(server_text))

    ok = _check_or_write(SERVER_JSON_PATH, server_text, check=args.check)
    ok &= _check_or_write(MCP_TOOLS_MD_PATH, tools_text, check=args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
