#!/usr/bin/env python3
"""Generate ``docs/README.md`` from ``docs/manifest.yaml``.

Module: scripts.gen_docs_index
Depends: argparse, difflib, pathlib, re, sys, yaml

The docs index is the link graph for consumer and contributor pages. It is
regenerated from the manifest so RD2-RD4 can append rows without hand-editing
the index table.

Exports:
    main — regenerate (default) or ``--check`` the docs index.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "docs" / "manifest.yaml"
INDEX_PATH = REPO_ROOT / "docs" / "README.md"

_GENERATED_HEADER = "<!-- Generated by scripts/gen_docs_index.py — do not edit by hand. -->"


def _load_manifest() -> dict[str, Any]:
    data = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        msg = f"{MANIFEST_PATH}: did not parse as a mapping"
        raise TypeError(msg)
    return data


def _manifest_pages(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    pages = manifest.get("pages")
    if not isinstance(pages, list):
        msg = f"{MANIFEST_PATH}: missing pages: list"
        raise TypeError(msg)
    rows: list[dict[str, Any]] = []
    for row in pages:
        if not isinstance(row, dict):
            msg = f"{MANIFEST_PATH}: each pages row must be a mapping"
            raise TypeError(msg)
        path = row.get("path")
        if not isinstance(path, str) or not path.strip():
            msg = f"{MANIFEST_PATH}: each row needs a non-empty path:"
            raise TypeError(msg)
        rows.append(row)
    return rows


def _page_label(path: str) -> str:
    if path == "README.md":
        return "Landing README"
    name = Path(path).name
    if name == "README.md":
        return f"{Path(path).parent.name} README"
    return name.removesuffix(".md")


def _render_index(pages: list[dict[str, Any]]) -> str:
    lines = [
        _GENERATED_HEADER,
        "",
        "# mergeCraft documentation index",
        "",
        "Map of consumer and contributor pages tracked in "
        "[`docs/manifest.yaml`](manifest.yaml). Regenerate with "
        "`make docs`.",
        "",
        "| Page | Audience | Purpose |",
        "|------|----------|---------|",
    ]
    for row in sorted(pages, key=lambda item: str(item["path"])):
        path = str(row["path"])
        audience = str(row.get("audience", ""))
        purpose = str(row.get("purpose", "")).replace("|", "\\|")
        label = _page_label(path)
        lines.append(f"| [{label}]({path}) | {audience} | {purpose} |")
    lines.extend(
        [
            "",
            "## See also",
            "",
            "- [CONTRIBUTING.md](../CONTRIBUTING.md)",
            "- [REVIEW-CHECKS.md](../REVIEW-CHECKS.md)",
            "- [Landing README](../README.md)",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Regenerate (default) or ``--check`` ``docs/README.md`` from the manifest."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero (with a unified diff) when the index drifts from the manifest.",
    )
    args = parser.parse_args(argv)

    manifest = _load_manifest()
    pages = _manifest_pages(manifest)
    generated = _render_index(pages)
    current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.is_file() else ""

    if args.check:
        if generated == current:
            print(f"{INDEX_PATH.relative_to(REPO_ROOT)}: index matches docs/manifest.yaml")
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(INDEX_PATH),
            tofile=f"{INDEX_PATH} (generated)",
        )
        sys.stdout.writelines(diff)
        print(
            f"{INDEX_PATH.relative_to(REPO_ROOT)}: index drifted from docs/manifest.yaml"
            " (run: make docs)",
            file=sys.stderr,
        )
        return 1

    INDEX_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
