#!/usr/bin/env python3
"""Generate ``llms-full.txt`` — concatenated LLM documentation bundle.

Module: scripts.gen_llms_full
Depends: argparse, difflib, pathlib, sys

Concatenates core consumer and contributor pages with ``===== FILE: … =====``
headers. ``make llms`` / ``make llms-check`` call this entry point; ``make docs``
folds it into the unified docs regeneration gate.

Exports:
    main — regenerate (default) or ``--check`` ``llms-full.txt``.
    OUTPUT_PATH — repo-root path written by default (overridable in tests).
    LLMS_FULL_PATHS — ordered list of relative paths concatenated into the bundle.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "llms-full.txt"

_GENERATED_HEADER = "<!-- Generated by scripts/gen_llms_full.py — do not edit by hand. -->"

LLMS_FULL_PATHS: tuple[str, ...] = (
    "README.md",
    "AGENTS.md",
    "REVIEW-CHECKS.md",
    "docs/ANALYZERS.md",
    "docs/REVIEW-DOCTRINE.md",
    "docs/TRACING.md",
    "docs/install.md",
    "docs/authentication.md",
)


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _render_llms_full() -> str:
    parts = [_GENERATED_HEADER, ""]
    for rel_path in LLMS_FULL_PATHS:
        path = REPO_ROOT / rel_path
        if not path.is_file():
            msg = f"missing {rel_path} required for llms-full.txt"
            raise FileNotFoundError(msg)
        parts.extend(
            [
                f"===== FILE: {rel_path} =====",
                "",
                path.read_text(encoding="utf-8").rstrip(),
                "",
            ]
        )
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Regenerate (default) or ``--check`` ``llms-full.txt``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero (with a unified diff) when llms-full.txt drifts.",
    )
    args = parser.parse_args(argv)

    generated = _render_llms_full()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""

    if args.check:
        if generated == current:
            print(f"{_display_path(OUTPUT_PATH)}: llms-full bundle matches sources")
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(OUTPUT_PATH),
            tofile=f"{OUTPUT_PATH} (generated)",
        )
        sys.stdout.writelines(diff)
        print(
            f"{_display_path(OUTPUT_PATH)}: llms-full bundle drifted (run: make llms)",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {_display_path(OUTPUT_PATH)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
