#!/usr/bin/env python3
"""Generate ``docs/support-matrix.md`` — six-axis consumer support matrix.

Module: scripts.gen_support_matrix
Depends: argparse, difflib, pathlib, sys,
    mergecraft.analyzers.registry, mergecraft.models, mergecraft.scm.webhooks

Builds OS, SCM, language, analyzer, provider, and model tables from live
catalogs so ``make docs-check`` fails when those sources drift. File 8 RV4
extends this generator to add a recommended-model column.

Exports:
    main — regenerate (default) or ``--check`` ``docs/support-matrix.md``.
    OUTPUT_PATH — repo-root path written by default (overridable in tests).
    gen_support_matrix — render the page body (entry point for RV4).
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from mergecraft.analyzers.registry import load_catalog
from mergecraft.models import PROVIDERS
from mergecraft.scm.webhooks import SUPPORTED_WEBHOOK_PROVIDERS

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "support-matrix.md"

_GENERATED_HEADER = "<!-- Generated by scripts/gen_support_matrix.py — do not edit by hand. -->"

# Action + CLI platforms. Matches ``provision_platform_key`` plus the Action
# runner; Windows is listed so the OS axis is explicit rather than omitted.
_OS_ROWS: tuple[tuple[str, str, str], ...] = (
    ("Linux (`linux/amd64`, `ubuntu-latest`)", "GitHub Action, Docker, CLI", "Supported"),
    ("Linux (`linux/arm64`)", "Docker image / CLI where published", "Supported"),
    ("macOS (`darwin-arm64`, `darwin-amd64`)", "Local CLI", "Supported"),
    ("Windows", "Action and CLI", "Not supported"),
)


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|")


def _table(headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("------" for _ in headers) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_md_cell(cell) for cell in row) + " |")
    return "\n".join(lines)


def gen_support_matrix() -> str:
    """Render the six-axis support matrix markdown page."""
    catalog = load_catalog()
    languages = sorted({lang for manifest in catalog for lang in manifest.languages if lang})
    analyzer_rows = [
        (
            f"`{manifest.id}`",
            ", ".join(manifest.languages) if manifest.languages else "any / universal",
            manifest.category,
            "auto" if manifest.default_enabled == "auto" else str(manifest.default_enabled),
        )
        for manifest in catalog
    ]
    provider_rows = [
        (f"`{key}`", config.display_name, ", ".join(f"`{env}`" for env in config.env_vars))
        for key, config in PROVIDERS.items()
    ]
    model_rows: list[tuple[str, ...]] = []
    for provider_key, config in PROVIDERS.items():
        for model_id, defn in config.models.items():
            if defn.hidden:
                continue
            notes = "preferred" if defn.preferred else "—"
            model_rows.append((f"`{provider_key}/{model_id}`", f"`{provider_key}`", notes))

    scm_rows = [
        (f"`{name}`", "Webhook + review ingress", "Supported")
        for name in sorted(SUPPORTED_WEBHOOK_PROVIDERS)
    ]
    scm_rows.append(("`bitbucket`", "Webhook ingress", "Not supported"))

    language_rows = [(lang, "Analyzer catalog `languages:`") for lang in languages]

    return "\n".join(
        [
            _GENERATED_HEADER,
            "",
            "# Support matrix",
            "",
            "Generated six-axis support matrix (OS, SCM, languages, analyzers,",
            "providers, models). **Do not edit this file by hand** — regenerate",
            "with `make docs`. Covered by `make docs-check`. Maintainer harness",
            "notes stay in [compatibility-matrix.md](compatibility-matrix.md).",
            "",
            "## OS",
            "",
            _table(("OS", "Surface", "Status"), list(_OS_ROWS)),
            "",
            "## SCM",
            "",
            _table(("SCM", "Role", "Status"), scm_rows),
            "",
            "## Languages",
            "",
            "Union of `languages:` on shipped analyzer catalog manifests.",
            "Analyzers with an empty language list are universal (any language).",
            "",
            _table(("Language", "Source"), language_rows),
            "",
            "## Analyzers",
            "",
            "Shipped catalog ids. The full catalog page is [ANALYZERS.md](ANALYZERS.md).",
            "",
            _table(("Analyzer", "Language", "Category", "Default"), analyzer_rows),
            "",
            "## Providers",
            "",
            "BYOK provider keys from the model catalog (`mergecraft.models.PROVIDERS`).",
            "",
            _table(("Provider", "Display name", "Credential env"), provider_rows),
            "",
            "## Models",
            "",
            "Non-hidden slugs from the same catalog. File 8 RV4 will add a",
            "recommended-model column here.",
            "",
            _table(("Model", "Provider", "Notes"), model_rows),
            "",
        ]
    )


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    """Regenerate (default) or ``--check`` ``docs/support-matrix.md``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero (with a unified diff) when the support matrix drifts.",
    )
    args = parser.parse_args(argv)

    generated = gen_support_matrix()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""

    if args.check:
        if generated == current:
            print(f"{_display_path(OUTPUT_PATH)}: support matrix matches catalogs")
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(OUTPUT_PATH),
            tofile=f"{OUTPUT_PATH} (generated)",
        )
        sys.stdout.writelines(diff)
        print(
            f"{_display_path(OUTPUT_PATH)}: support matrix drifted (run: make docs)",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {_display_path(OUTPUT_PATH)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
