"""Git identity + askpass configuration for agent runs."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from loguru import logger

if TYPE_CHECKING:
    from mergecraft.mcp.tool_state import ToolState
    from mergecraft.types import ShellPermission
    from mergecraft.utils.github import GitHubClient

ShellPerm = Literal["disabled", "restricted", "enabled"]

MERGECRAFT_BOT_EMAIL = "226033991+mergecraft[bot]@users.noreply.github.com"
MERGECRAFT_BOT_NAME = "mergecraft[bot]"


def create_temp_directory() -> str:
    import tempfile

    shared = tempfile.mkdtemp(prefix="mergecraft-")
    os.environ["MERGECRAFT_TEMP_DIR"] = shared
    logger.info("» created temp dir at {}", shared)
    return shared


def _git_config(repo_dir: str, key: str, value: str) -> None:
    subprocess.run(
        ["git", "config", "--local", key, value],
        cwd=repo_dir,
        check=False,
        capture_output=True,
        text=True,
    )


def _git_get(repo_dir: str, key: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "config", "--get", key],
            cwd=repo_dir,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError, OSError:
        return ""


def write_askpass_script(tmpdir: str, token: str) -> str:
    """Write a GIT_ASKPASS helper returning ``x-access-token`` + the token.

    Git invokes ``GIT_ASKPASS`` twice — once for the username prompt, once for the
    password — passing the prompt text as ``$1``. Returning the token for *both*
    yields ``https://<token>:<token>@github.com``, which GitHub accepts only
    intermittently (token-as-username is not the documented form) and otherwise
    rejects with ``remote: invalid credentials``. Emit the documented pair
    instead: username ``x-access-token``, password ``<token>``.
    """
    path = Path(tmpdir) / "git-askpass.sh"
    path.write_text(
        "#!/bin/sh\n"
        "# generated by mergecraft — do not commit\n"
        'case "$1" in\n'
        "  Username*) echo 'x-access-token' ;;\n"
        f'  *) echo "{token}" ;;\n'
        "esac\n",
        encoding="utf-8",
    )
    path.chmod(0o700)
    return str(path)


def setup_git(
    *,
    git_token: str,
    owner: str,
    name: str,
    tool_state: ToolState,
    shell: ShellPerm | ShellPermission = "restricted",
    tmpdir: str | None = None,
    octokit: GitHubClient | None = None,
    post_checkout_script: str | None = None,
) -> None:
    """Configure git identity and askpass for the primary working tree."""
    from mergecraft.mcp.tool_state import primary_repo_state, require_repo_state

    repo_dir = os.getcwd()
    try:
        repo_state = require_repo_state(tool_state, owner, name)
    except RuntimeError:
        repo_state = primary_repo_state(tool_state)
    repo_state.dir = repo_dir

    logger.info("» setting up git configuration...")
    current_email = _git_get(repo_dir, "user.email")
    should_set = (
        not current_email or current_email == "github-actions[bot]@users.noreply.github.com"
    )
    if should_set:
        _git_config(repo_dir, "user.email", MERGECRAFT_BOT_EMAIL)
        _git_config(repo_dir, "user.name", MERGECRAFT_BOT_NAME)
        logger.debug("» git user configured (using defaults)")
    else:
        logger.debug("» git user already configured ({}), skipping", current_email)

    if shell == "disabled":
        _git_config(repo_dir, "core.hooksPath", "/dev/null")
        logger.debug("» git hooks disabled (shell=disabled)")

    temp = tmpdir or os.environ.get("MERGECRAFT_TEMP_DIR") or create_temp_directory()
    askpass = write_askpass_script(temp, git_token)
    os.environ["GIT_ASKPASS"] = askpass
    os.environ["GIT_TERMINAL_PROMPT"] = "0"
    # Prefer HTTPS push URL with token-less host (askpass supplies creds).
    push_url = f"https://github.com/{owner}/{name}.git"
    repo_state.push_url = push_url
    logger.info("» git askpass configured for {}", f"{owner}/{name}")

    _ = octokit  # reserved for future post-checkout remote probes
    if post_checkout_script:
        logger.debug("» post_checkout_script present (deferred to MCP checkout hooks)")


def wipe_runner_leak_surface() -> None:
    """Best-effort wipe of known credential leak paths under ``$RUNNER_TEMP``."""
    runner_temp = os.environ.get("RUNNER_TEMP")
    if not runner_temp:
        return
    preserve: set[str] = set()
    for env_var in (
        "GITHUB_OUTPUT",
        "GITHUB_ENV",
        "GITHUB_PATH",
        "GITHUB_STATE",
        "GITHUB_STEP_SUMMARY",
    ):
        path = os.environ.get(env_var)
        if path:
            try:
                preserve.add(str(Path(path).resolve()))
            except OSError:
                preserve.add(path)

    wiped: list[str] = []

    def try_unlink(path: Path) -> None:
        try:
            resolved = str(path.resolve())
        except OSError:
            resolved = str(path)
        if resolved in preserve or str(path) in preserve:
            return
        try:
            path.unlink(missing_ok=True)
            wiped.append(str(path))
        except OSError:
            pass

    file_commands = Path(runner_temp) / "_runner_file_commands"
    if file_commands.is_dir():
        for entry in file_commands.iterdir():
            try_unlink(entry)
    root = Path(runner_temp)
    if root.is_dir():
        for entry in root.iterdir():
            name = entry.name
            if name.endswith(".sh") or (
                name.startswith("git-credentials-") and name.endswith(".config")
            ):
                try_unlink(entry)

    if wiped:
        logger.info("» wiped {} leak-surface file(s) from $RUNNER_TEMP", len(wiped))


__all__ = [
    "MERGECRAFT_BOT_EMAIL",
    "MERGECRAFT_BOT_NAME",
    "create_temp_directory",
    "setup_git",
    "wipe_runner_leak_surface",
    "write_askpass_script",
]
